### ISSUE TITLE
Test Results

### ISSUE THREAD

**Issue by wangyu0423** [HanjiangHu/DIFL-FCL#2]
How do you get the results in regimes of high precision (HP), medium precision (MP) and coarse precision (CP) respectively? Thank you

**Comment by HanjiangHu** [comment]
The results under different precision are from[ the official website of long-term visual localization](https://www.visuallocalization.net/benchmark/), where the retrieval results from this repository are submitted and evaluated automatically.

**Comment by xiaomanZ613** [comment]
Hi, excuse me.
when I save the test result as a txt file and submit it to the official website of the benchmark, the submissions failed to be processed.
Thank you!
